# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package.json and lock file if any
COPY package.json ./
COPY bun.lock ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not required for stdio, but just in case)

CMD [ "node", "build/index.js" ]
